# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.cors  _listener:
        class: DevrestoBundle\EventListener\CorsListener
        tags:
        - { name: kernel.event_listener, event: kernel.response,   method: onKernelResponse }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
